# Node image with Alpine Linux
FROM node:lts-alpine

ARG NEXT_PUBLIC_URI
ARG NEXT_PUBLIC_API_URI
ARG NEXT_PUBLIC_AUTHENTIK_CLIENT_ID
ARG AUTHENTIK_CLIENT_SECRET
ARG NEXT_PUBLIC_AUTHENTIK_URI

ENV NEXT_PUBLIC_URI=$NEXT_PUBLIC_URI
ENV NEXT_PUBLIC_API_URI=$NEXT_PUBLIC_API_URI
ENV NEXT_PUBLIC_AUTHENTIK_CLIENT_ID=$NEXT_PUBLIC_AUTHENTIK_CLIENT_ID
ENV AUTHENTIK_CLIENT_SECRET=$AUTHENTIK_CLIENT_SECRET
ENV NEXT_PUBLIC_AUTHENTIK_URI=$NEXT_PUBLIC_AUTHENTIK_URI

# Workdir
WORKDIR /app

# Copies package.json and package-lock.json
COPY package*.json ./

# Installs dependencies
RUN npm install

# Copies the rest of the UI source code
COPY . .

RUN npm run build

# Exposes port 3000
EXPOSE 3000

CMD npm start
