export { default as createForm } from './post.ts'
export { default as getForms } from './get.ts'
export { default as getForm } from './getOne.ts'
export { default as updateForm } from './put.ts'
export { default as deleteForm } from './delete.ts'